/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as LifestyleRouteImport } from './routes/lifestyle'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as ApiPublicHooksSheetsSyncRouteImport } from './routes/api/public/hooks/sheets-sync'
import { Route as ApiPublicHooksScheduledRouteImport } from './routes/api/public/hooks/scheduled'

const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const LifestyleRoute = LifestyleRouteImport.update({
  id: '/lifestyle',
  path: '/lifestyle',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicHooksSheetsSyncRoute =
  ApiPublicHooksSheetsSyncRouteImport.update({
    id: '/api/public/hooks/sheets-sync',
    path: '/api/public/hooks/sheets-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksScheduledRoute = ApiPublicHooksScheduledRouteImport.update({
  id: '/api/public/hooks/scheduled',
  path: '/api/public/hooks/scheduled',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/lifestyle': typeof LifestyleRoute
  '/patient': typeof PatientRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/hooks/scheduled': typeof ApiPublicHooksScheduledRoute
  '/api/public/hooks/sheets-sync': typeof ApiPublicHooksSheetsSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/lifestyle': typeof LifestyleRoute
  '/patient': typeof PatientRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/hooks/scheduled': typeof ApiPublicHooksScheduledRoute
  '/api/public/hooks/sheets-sync': typeof ApiPublicHooksSheetsSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/lifestyle': typeof LifestyleRoute
  '/patient': typeof PatientRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/hooks/scheduled': typeof ApiPublicHooksScheduledRoute
  '/api/public/hooks/sheets-sync': typeof ApiPublicHooksSheetsSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/lifestyle'
    | '/patient'
    | '/admin/dashboard'
    | '/admin/'
    | '/api/public/hooks/scheduled'
    | '/api/public/hooks/sheets-sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/lifestyle'
    | '/patient'
    | '/admin/dashboard'
    | '/admin'
    | '/api/public/hooks/scheduled'
    | '/api/public/hooks/sheets-sync'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/lifestyle'
    | '/patient'
    | '/admin/dashboard'
    | '/admin/'
    | '/api/public/hooks/scheduled'
    | '/api/public/hooks/sheets-sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  LifestyleRoute: typeof LifestyleRoute
  PatientRoute: typeof PatientRoute
  ApiPublicHooksScheduledRoute: typeof ApiPublicHooksScheduledRoute
  ApiPublicHooksSheetsSyncRoute: typeof ApiPublicHooksSheetsSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lifestyle': {
      id: '/lifestyle'
      path: '/lifestyle'
      fullPath: '/lifestyle'
      preLoaderRoute: typeof LifestyleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/hooks/sheets-sync': {
      id: '/api/public/hooks/sheets-sync'
      path: '/api/public/hooks/sheets-sync'
      fullPath: '/api/public/hooks/sheets-sync'
      preLoaderRoute: typeof ApiPublicHooksSheetsSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/scheduled': {
      id: '/api/public/hooks/scheduled'
      path: '/api/public/hooks/scheduled'
      fullPath: '/api/public/hooks/scheduled'
      preLoaderRoute: typeof ApiPublicHooksScheduledRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  LifestyleRoute: LifestyleRoute,
  PatientRoute: PatientRoute,
  ApiPublicHooksScheduledRoute: ApiPublicHooksScheduledRoute,
  ApiPublicHooksSheetsSyncRoute: ApiPublicHooksSheetsSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
